# Describes the format for available alarm control panel services

alarm_disarm:
  target:
    entity: &alarm_entity
      domain: alarm_control_panel
  fields: &common_fields
    code:
      example: "1234"
      selector:
        text:

alarm_arm_custom_bypass:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS
  fields: *common_fields

alarm_arm_home:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_HOME
  fields: *common_fields

alarm_arm_away:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_AWAY
  fields: *common_fields
alarm_arm_night:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_NIGHT
  fields: *common_fields

alarm_arm_vacation:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_VACATION
  fields: *common_fields

alarm_trigger:
  target:
    entity:
      <<: *alarm_entity
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.TRIGGER
  fields: *common_fields
